import { Deal } from "./types";

// Placeholder deals for local UI development, in the shape the real ingestion
// pipeline (services/ingest-flights, services/ingest-cruises) will produce.
//
// Deliberately spread across several origin cities per market, three
// currencies and a rolling set of departure months, so the month / budget /
// origin filters all have something to bite on before the live pipeline has
// accumulated enough price history to publish real deals.
export const mockDeals: Deal[] = [
  // ---------------------------------------------------------------- United States
  {
    id: "flight-us-1",
    mode: "FLIGHT",
    title: "1-stop to Paris",
    destination: "Paris, France",
    originAirportOrPort: "JFK",
    originCity: "New York",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "Air France",
    departureMonth: "2026-09",
    departureAt: "2026-09-14T00:00:00Z",
    originalPrice: 980,
    dealPrice: 520,
    currency: "USD",
    discountPct: 47,
    affiliateUrl: "#",
    publishedAt: "2026-08-22T00:00:00Z",
  },
  {
    id: "flight-us-2",
    mode: "FLIGHT",
    title: "1-stop to Tokyo",
    destination: "Tokyo, Japan",
    originAirportOrPort: "JFK",
    originCity: "New York",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "ANA",
    departureMonth: "2026-10",
    departureAt: "2026-10-08T00:00:00Z",
    originalPrice: 1450,
    dealPrice: 780,
    currency: "USD",
    discountPct: 46,
    affiliateUrl: "#",
    publishedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "flight-us-3",
    mode: "FLIGHT",
    title: "1-stop to Lisbon",
    destination: "Lisbon, Portugal",
    originAirportOrPort: "JFK",
    originCity: "New York",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "TAP Air Portugal",
    departureMonth: "2026-11",
    departureAt: "2026-11-05T00:00:00Z",
    originalPrice: 940,
    dealPrice: 410,
    currency: "USD",
    discountPct: 56,
    affiliateUrl: "#",
    publishedAt: "2026-08-14T00:00:00Z",
  },
  {
    id: "flight-us-4",
    mode: "FLIGHT",
    title: "Non-stop to Tokyo",
    destination: "Tokyo, Japan",
    originAirportOrPort: "LAX",
    originCity: "Los Angeles",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: true,
    airline: "Japan Airlines",
    departureMonth: "2026-10",
    departureAt: "2026-10-19T00:00:00Z",
    originalPrice: 1200,
    dealPrice: 620,
    currency: "USD",
    discountPct: 48,
    affiliateUrl: "#",
    publishedAt: "2026-08-24T00:00:00Z",
  },
  {
    id: "flight-us-5",
    mode: "FLIGHT",
    title: "1-stop to Barcelona",
    destination: "Barcelona, Spain",
    originAirportOrPort: "LAX",
    originCity: "Los Angeles",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: false,
    airline: "Iberia",
    departureMonth: "2027-03",
    departureAt: "2027-03-11T00:00:00Z",
    originalPrice: 1100,
    dealPrice: 590,
    currency: "USD",
    discountPct: 46,
    affiliateUrl: "#",
    publishedAt: "2026-08-25T00:00:00Z",
  },
  {
    id: "flight-us-6",
    mode: "FLIGHT",
    title: "Non-stop to Cancun",
    destination: "Cancun, Mexico",
    originAirportOrPort: "ORD",
    originCity: "Chicago",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: false,
    airline: "United",
    departureMonth: "2027-01",
    departureAt: "2027-01-17T00:00:00Z",
    originalPrice: 620,
    dealPrice: 310,
    currency: "USD",
    discountPct: 50,
    affiliateUrl: "#",
    publishedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "flight-us-7",
    mode: "FLIGHT",
    title: "1-stop to Barcelona",
    destination: "Barcelona, Spain",
    originAirportOrPort: "JFK",
    originCity: "New York",
    originCountry: "United States",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "TAP Air Portugal",
    departureMonth: "2027-04",
    departureAt: "2027-04-09T00:00:00Z",
    originalPrice: 890,
    dealPrice: 445,
    currency: "USD",
    discountPct: 50,
    affiliateUrl: "#",
    publishedAt: "2026-08-26T00:00:00Z",
  },
  {
    id: "cruise-us-1",
    mode: "CRUISE",
    title: "7-night Caribbean cruise",
    destination: "Eastern Caribbean",
    originAirportOrPort: "Miami, FL",
    originCity: "Miami",
    originCountry: "United States",
    cabinClass: "BALCONY",
    nights: 7,
    departureMonth: "2026-12",
    departureAt: "2026-12-06T00:00:00Z",
    originalPrice: 1800,
    dealPrice: 899,
    currency: "USD",
    discountPct: 50,
    affiliateUrl: "#",
    publishedAt: "2026-08-12T00:00:00Z",
  },

  // --------------------------------------------------------------- United Kingdom
  {
    id: "flight-uk-1",
    mode: "FLIGHT",
    title: "Non-stop to Dubai",
    destination: "Dubai, UAE",
    originAirportOrPort: "LHR",
    originCity: "London",
    originCountry: "United Kingdom",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: true,
    airline: "Emirates",
    departureMonth: "2026-09",
    departureAt: "2026-09-22T00:00:00Z",
    originalPrice: 720,
    dealPrice: 355,
    currency: "GBP",
    discountPct: 51,
    affiliateUrl: "#",
    publishedAt: "2026-08-21T00:00:00Z",
  },
  {
    id: "flight-uk-2",
    mode: "FLIGHT",
    title: "1-stop to Bangkok",
    destination: "Bangkok, Thailand",
    originAirportOrPort: "LHR",
    originCity: "London",
    originCountry: "United Kingdom",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "Qatar Airways",
    departureMonth: "2026-11",
    departureAt: "2026-11-12T00:00:00Z",
    originalPrice: 810,
    dealPrice: 430,
    currency: "GBP",
    discountPct: 47,
    affiliateUrl: "#",
    publishedAt: "2026-08-19T00:00:00Z",
  },
  {
    id: "flight-uk-3",
    mode: "FLIGHT",
    title: "1-stop to Cape Town",
    destination: "Cape Town, South Africa",
    originAirportOrPort: "LHR",
    originCity: "London",
    originCountry: "United Kingdom",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "Lufthansa",
    departureMonth: "2027-01",
    departureAt: "2027-01-24T00:00:00Z",
    originalPrice: 950,
    dealPrice: 520,
    currency: "GBP",
    discountPct: 45,
    affiliateUrl: "#",
    publishedAt: "2026-08-18T00:00:00Z",
  },
  {
    id: "flight-uk-4",
    mode: "FLIGHT",
    title: "Non-stop to New York",
    destination: "New York, USA",
    originAirportOrPort: "LHR",
    originCity: "London",
    originCountry: "United Kingdom",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: false,
    airline: "British Airways",
    departureMonth: "2026-10",
    departureAt: "2026-10-15T00:00:00Z",
    originalPrice: 640,
    dealPrice: 310,
    currency: "GBP",
    discountPct: 52,
    affiliateUrl: "#",
    publishedAt: "2026-08-26T00:00:00Z",
  },
  {
    id: "flight-uk-5",
    mode: "FLIGHT",
    title: "Non-stop to Barcelona",
    destination: "Barcelona, Spain",
    originAirportOrPort: "MAN",
    originCity: "Manchester",
    originCountry: "United Kingdom",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: false,
    airline: "Jet2",
    departureMonth: "2026-09",
    departureAt: "2026-09-30T00:00:00Z",
    originalPrice: 210,
    dealPrice: 79,
    currency: "GBP",
    discountPct: 62,
    affiliateUrl: "#",
    publishedAt: "2026-08-25T00:00:00Z",
  },
  {
    id: "flight-uk-6",
    mode: "FLIGHT",
    title: "1-stop to Dubai",
    destination: "Dubai, UAE",
    originAirportOrPort: "MAN",
    originCity: "Manchester",
    originCountry: "United Kingdom",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "Turkish Airlines",
    departureMonth: "2027-02",
    departureAt: "2027-02-13T00:00:00Z",
    originalPrice: 690,
    dealPrice: 365,
    currency: "GBP",
    discountPct: 47,
    affiliateUrl: "#",
    publishedAt: "2026-08-16T00:00:00Z",
  },
  {
    id: "cruise-uk-1",
    mode: "CRUISE",
    title: "10-night Mediterranean cruise",
    destination: "Western Mediterranean",
    originAirportOrPort: "Southampton",
    originCity: "Southampton",
    originCountry: "United Kingdom",
    cabinClass: "OCEANVIEW",
    nights: 10,
    departureMonth: "2027-04",
    departureAt: "2027-04-18T00:00:00Z",
    originalPrice: 1400,
    dealPrice: 700,
    currency: "GBP",
    discountPct: 50,
    affiliateUrl: "#",
    publishedAt: "2026-08-15T00:00:00Z",
  },

  // ----------------------------------------------------------------------- India
  {
    id: "flight-in-1",
    mode: "FLIGHT",
    title: "1-stop to Bangkok",
    destination: "Bangkok, Thailand",
    originAirportOrPort: "DEL",
    originCity: "Delhi",
    originCountry: "India",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "Vietnam Airlines",
    departureMonth: "2026-09",
    departureAt: "2026-09-18T00:00:00Z",
    originalPrice: 48000,
    dealPrice: 24500,
    currency: "INR",
    discountPct: 49,
    affiliateUrl: "#",
    publishedAt: "2026-08-24T00:00:00Z",
  },
  {
    id: "flight-in-2",
    mode: "FLIGHT",
    title: "Non-stop to Dubai",
    destination: "Dubai, UAE",
    originAirportOrPort: "DEL",
    originCity: "Delhi",
    originCountry: "India",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: true,
    airline: "Emirates",
    departureMonth: "2026-10",
    departureAt: "2026-10-11T00:00:00Z",
    originalPrice: 42000,
    dealPrice: 21000,
    currency: "INR",
    discountPct: 50,
    affiliateUrl: "#",
    publishedAt: "2026-08-22T00:00:00Z",
  },
  {
    id: "flight-in-3",
    mode: "FLIGHT",
    title: "1-stop to Singapore",
    destination: "Singapore",
    originAirportOrPort: "DEL",
    originCity: "Delhi",
    originCountry: "India",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: false,
    airline: "AirAsia X",
    departureMonth: "2026-12",
    departureAt: "2026-12-21T00:00:00Z",
    originalPrice: 52000,
    dealPrice: 26000,
    currency: "INR",
    discountPct: 50,
    affiliateUrl: "#",
    publishedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "flight-in-4",
    mode: "FLIGHT",
    title: "1-stop to Bali",
    destination: "Bali, Indonesia",
    originAirportOrPort: "BOM",
    originCity: "Mumbai",
    originCountry: "India",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "Singapore Airlines",
    departureMonth: "2026-11",
    departureAt: "2026-11-27T00:00:00Z",
    originalPrice: 61000,
    dealPrice: 31000,
    currency: "INR",
    discountPct: 49,
    affiliateUrl: "#",
    publishedAt: "2026-08-17T00:00:00Z",
  },
  {
    id: "flight-in-5",
    mode: "FLIGHT",
    title: "1-stop to London",
    destination: "London, UK",
    originAirportOrPort: "BOM",
    originCity: "Mumbai",
    originCountry: "India",
    cabinClass: "ECONOMY",
    stops: 1,
    baggageIncluded: true,
    airline: "British Airways",
    departureMonth: "2027-03",
    departureAt: "2027-03-06T00:00:00Z",
    originalPrice: 78000,
    dealPrice: 39500,
    currency: "INR",
    discountPct: 49,
    affiliateUrl: "#",
    publishedAt: "2026-08-13T00:00:00Z",
  },
  {
    id: "flight-in-6",
    mode: "FLIGHT",
    title: "Non-stop to Tokyo",
    destination: "Tokyo, Japan",
    originAirportOrPort: "DEL",
    originCity: "Delhi",
    originCountry: "India",
    cabinClass: "ECONOMY",
    stops: 0,
    baggageIncluded: true,
    airline: "Japan Airlines",
    departureMonth: "2027-02",
    departureAt: "2027-02-20T00:00:00Z",
    originalPrice: 75000,
    dealPrice: 36500,
    currency: "INR",
    discountPct: 51,
    affiliateUrl: "#",
    publishedAt: "2026-08-10T00:00:00Z",
  },
];
